const express = require('express')
const router = express.Router()
const {create} = require('./create')
const {filter} = require('./filter')
const {doImport, doUpload} = require('./import')
router.post('/create', create)
router.post('/filter', filter)
router.post('/import', doImport)
router.post('/upload', doUpload)
module.exports = router